name: electric_icons
description: Electrical icons
version: 2.0.2
homepage: https://github.com/brettpappas/electric_icons

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Electrical
      fonts:
        - asset: packages/electric_icons/fonts/Electrical.ttf
